esphome:
  name: lampify-controller
  friendly_name: Lampify Controller

esp32:
  board: esp32dev
  framework:
    type: esp-idf

logger:

api:
  encryption:
    key: !secret api_key

ota:
  platform: esphome
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Required for BLE
esp32_ble:

# External component
external_components:
  - source: github://steffen-heil-secforge/esphome-lampify
    components: [lampify]

# Core lampify component (device_id is optional, can be set from HA)
lampify:
  # device_id: 0x1234  # Uncomment to preset device ID

# Number entity to set device ID from Home Assistant
number:
  - platform: lampify
    name: "Lamp Device ID"

# Button to pair with lamp
button:
  - platform: lampify
    name: "Pair Lamp"

# Light entity with brightness and color temperature
light:
  - platform: lampify
    name: "Desk Lamp"
